---
# Configuration of the Cycloid stack
name: 'Scaleway Kapsule'
canonical: 'stack-kapsule'
status: 'private'
description: |
  Used to deploy a Scaleway Kubernetes Kapsule cluster with one or more node pools.
keywords:
  - 'kubernetes'
  - 'kapsule'
  - 'provider:scw'
author: 'Cycloid'
image: |
  https://raw.githubusercontent.com/cycloid-community-catalog/stack-kapsule/master/icon.png
technologies:
  - technology: Scaleway Kubernetes Kapsule
    version: 1.19

config:
  # Configuration of the CI pipeline
  pipeline:
    pipeline:
      path: 'pipeline/pipeline.yml'
    variables:
      path: 'pipeline/variables.sample.yml'
      destination: '($ project $)/pipeline/($ environment $)/variables.yml'

  # Configuration of terraform to setup the infrastructure
  terraform:
    kapsule:
      path: 'terraform/kapsule.tf.sample'
      destination: '($ project $)/terraform/($ environment $)/kapsule.tf'
